# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7adb44a55fac715be537bd292d721438b74cafdf9b2c530054e760ead2abac92ba1c03391c6cacb1dedc411bee95b8a3ee5f372cd83626a9fbc7517ce74fc177

test:
  secret_key_base: d8a446f71edde0132c8da29275872522087707756e04e292ff197c94190d5100b9e9b4f75595b88fa9588c3b7284bc897021ef4c1421384d859797f504faf324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
